name: Publish docker image on Github Container Registry
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the docker image
        run: docker build . --tag ghcr.io/lbenicio/v2-blog:latest --tag ghcr.io/lbenicio/v2-blog:${{ github.sha }}
      - name: Publish the docker image
        run: docker push ghcr.io/lbenicio/v2-blog --all-tags